<a href="https://colab.research.google.com/github/prisar/ai/blob/main/project_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###tinygrad

In [1]:
!git clone https://github.com/geohot/tinygrad.git

Cloning into 'tinygrad'...
remote: Enumerating objects: 12727, done.
remote: Counting objects: 100% (1013/1013), done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 12727 (delta 860), reused 847 (delta 761), pack-reused 11714
Receiving objects: 100% (12727/12727), 16.78 MiB | 35.79 MiB/s, done.
Resolving deltas: 100% (8933/8933), done.


In [2]:
cd tinygrad

/content/tinygrad


In [7]:
!pip install -e .

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Obtaining file:///content/tinygrad
  Preparing metadata (setup.py) ... done
  Running setup.py develop for tinygrad


In [8]:
from tinygrad.tensor import Tensor

x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0,0,-2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()

print(x.grad.numpy())  # dz/dx
print(y.grad.numpy())  # dz/dy

[[ 2.  2.  2.]
 [ 0.  0.  0.]
 [-2. -2. -2.]]
[[1. 1. 1.]]


In [9]:
!DEBUG=3 OPTLOCAL=1 python3 -c "from tinygrad.tensor import Tensor;
N = 1024; a, b = Tensor.randn(N, N), Tensor.randn(N, N);
c = (a.reshape(N, 1, N) * b.permute(1,0).reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"

SyntaxError: ignored